name: sero
description: "Emotion-Aware Voice Assistant built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  provider: ^6.1.2
  permission_handler: ^11.3.1
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true